language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAI5PATJK255WPJCLA
  secret_access_key:
    secure: OWdNUbHv3DQEuE1Kp8huzHoaGFnQwLfUsiyTpT+7JHgucDgr245j8ZEv5OCrfroZ1657eVp/WYySJHlPvPOZiCiYs5WutvLWK12DOdbkskxA0Ok3XwsE6ret9yJJ2aGJVEvtN0xf7Dyy9qH0l+plaSA5yyR4vLxGe4ejyn7QUe4wEtM5udivmhBw1PyRn5bmkMSbIUmr5NtTkFtCfPH6Hnt/a5CioqCurwHKPnrtek5v3OW3CYsVqBnQWk93KWxmueWohDM9K9/WngCQX5bXsGGWVm9xdXhjQZiyb93Tae0PUrdjmQvJVGfJSFOzhlGFSRmdQJwmRHendYuHX8gz5p/CFIt1wLe2TtlapRuMjc12BvnEDuJkfICAqPBcDGi4wijXNnvR5A44hRQDJ+ISktBKAxP8GS1+oMpAxGWskdIXdPQEfQ7dE1s4//YluvHZhM//IViv5RsUUc8g25aHk2eRlbCc3lDgnqqpNI4u3zXzsYbePSjPPn2nR6vLVuTNFXCqrnUsUgCWDVh2FLOiCUM26K6ld31nINnstrYtaeSMS6CDYIJhjpD8L8FvtqlOVE1Evu90AibZ4RxRDcbZpH8m5iM6VpkwwsJIX8gOrcmCjWF2/yHtBnojoe+sFcZl56+DMVNAicyflmu41I7ZeWs/85yxdtF+AHOxu++ZUDo=
  bucket: http://danielhtfan.com.s3-website.us-east-2.amazonaws.com
  acl: public_read
branches:
  only:
  - master
